spring:
  data:
    mongodb:
      uri: mongodb+srv://csj2702:tjdwns2702@cluster0.8vlwn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      database: breadstore
jjwt:
  access-token:
    expired-time: 720
    secret-key: access_secret
  refresh-token:
    expired-time: 720
    secret-key: refresh_secret

oauth:
  google:
    base-url: https://accounts.google.com
    login-uri: /o/oauth2/v2/auth
    token-url: https://oauth2.googleapis.com
    token-uri: /token
    client-id: 1
    client-secret: 1
    callback-url: http://localhost:8080/api/oauth/callback/google
    profile-url: https://oauth2.googleapis.com
    profile-uri: /tokeninfo
  kakao:
    base-url: https://kauth.kakao.com
    login-uri: /oauth/authorize
    token-uri: /oauth/token
    client-id: 1
    client-secret: 1
    callback-url: http://localhost:8080/api/oauth/callback/kakao
    profile-url: https://kapi.kakao.com
    profile-uri: /v2/user/me
  naver:
    base-url: https://nid.naver.com
    login-uri: /oauth2.0/authorize
    token-uri: /oauth2.0/token
    client-id: 1
    client-secret: 1
    callback-url: http://localhost:8080/api/oauth/callback/naver
    profile-url: https://openapi.naver.com
    profile-uri: /v1/nid/me
vword:
  domain: http://localhost:8080
  key: 1
  url: https://api.vworld.kr
  uri: /req/data
  common-params: request=GetFeature&data=LT_C_ADSIGG_INFO